project_id = "ktnqolddfsqkbqhmmiiz"

[functions.create-campaign-checkout]
verify_jwt = false

[functions.create-reward-setup]
verify_jwt = false

[functions.charge-reward-video]
verify_jwt = false

[functions.create-connect-account]
verify_jwt = false

[functions.request-payout]
verify_jwt = false

[functions.process-payout]
verify_jwt = false

[functions.delete-account]
verify_jwt = false
